# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you dont want to commit.
for file in ~/.{path,bash_prompt,exports,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

if [ ! -d ~/.layouts ]; then
	mkdir .layouts 
fi

if [ ! -d ~/bin ]; then
	mkdir ~/bin
fi

if [ ! -d ~/.fonts ]; then
	mkdir ~/.fonts
fi

if [ ! -d ~/.config ]; then
	mkdir ~/.config
fi

if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

if [ ! -d ~/.kwm ]; then
	mkdir ~/.kwm
fi

